parameters:
    kernel.include_core_classes: false

kernel.config: ~

web.config:
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    validation: { enabled: true, annotations: true }

web.templating: ~

## Twig Configuration
#twig.config:
#    auto_reload: true

## Doctrine Configuration
#doctrine.dbal:
#    dbname:   xxxxxxxx
#    user:     xxxxxxxx
#    password: ~

## Swiftmailer Configuration
#swift.mailer:
#    transport:  smtp
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx
