parameters:
    kernel.include_core_classes: false

kernel.config: ~
web.web: ~
web.templating: ~

propel.config:
  path:       %kernel.root_dir%/../src/vendor/propel
  phing_path: %kernel.root_dir%/../src/vendor/phing
