parameters:
    kernel.include_core_classes: false

kernel.config: ~

web.config:
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    validation: { enabled: true, annotations: true }

web.templating: ~
